"""PDF report generator using WeasyPrint. Returns PDF bytes."""

import base64
import html as html_lib

from app.agents.state import DetectedFinding
from app.services import storage
from app.core.logging_config import get_logger

logger = get_logger(__name__)

REPORT_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #1a1a2e; }}
  h1 {{ color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 10px; }}
  h2 {{ color: #0f3460; margin-top: 30px; }}
  .score {{ font-size: 48px; font-weight: bold; color: {score_color}; }}
  .score-label {{ font-size: 14px; color: #666; }}
  .finding {{ border: 1px solid #ddd; border-radius: 8px; padding: 16px; margin: 12px 0; }}
  .finding-header {{ display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }}
  .severity {{ padding: 2px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; color: white; }}
  .severity-high {{ background: #e74c3c; }}
  .severity-medium {{ background: #f39c12; }}
  .severity-low {{ background: #f1c40f; color: #333; }}
  .category {{ font-size: 12px; color: #888; }}
  .ccpa {{ font-size: 12px; color: #0f3460; font-weight: bold; }}
  .evidence {{ max-width: 100%; max-height: 300px; margin-top: 8px; border: 1px solid #eee; }}
  .ref {{ font-size: 13px; margin: 6px 0; }}
  .meta {{ font-size: 12px; color: #999; margin-top: 20px; }}
</style>
</head>
<body>
  <h1>Pattern Proof — Dark Pattern Audit Report</h1>
  <p><strong>Website:</strong> {url}</p>
  <p><strong>Pages analyzed:</strong> {page_count}</p>

  <div>
    <span class="score">{score}</span>
    <span class="score-label">/ 100 (higher is better — DPDP / CCPA 2023 compliance)</span>
  </div>

  <h2>Executive Summary</h2>
  <p>{summary}</p>

  <h2>Findings ({finding_count})</h2>
  {findings_html}

  <h2>References</h2>
  {references_html}

  <p class="meta">Generated by Pattern Proof — aligned to the CCPA 2023 Guidelines for Prevention
  and Regulation of Dark Patterns.</p>
</body>
</html>"""

FINDING_HTML = """<div class="finding">
  <div class="finding-header">
    <span class="severity severity-{severity}">{severity_upper}</span>
    <strong>{title}</strong>
    <span class="category">{category} / {dp_type}</span>
  </div>
  {ccpa_html}
  <p>{description}</p>
  {explanation_html}
  {evidence_html}
</div>"""


def _evidence_img(f: DetectedFinding) -> str:
    if not f.evidence_screenshot_path:
        return ""
    data = storage.download(f.evidence_screenshot_path)
    if not data:
        return ""
    b64 = base64.b64encode(data).decode()
    return f'<img class="evidence" src="data:image/png;base64,{b64}" alt="evidence"/>'


def build_html(
    url: str,
    page_count: int,
    score: int,
    summary: str,
    findings: list[DetectedFinding],
    references: list[dict],
) -> str:
    findings_html = "\n".join(
        FINDING_HTML.format(
            severity=f.severity,
            severity_upper=f.severity.upper(),
            title=html_lib.escape(f.title),
            category=f.category,
            dp_type=f.dp_type,
            ccpa_html=(
                f'<div class="ccpa">CCPA pattern: {f.ccpa_pattern.replace("_", " ").title()}</div>'
                if f.ccpa_pattern else ""
            ),
            description=html_lib.escape(f.description).replace("\n", "<br>"),
            explanation_html=(
                f"<p><em>{html_lib.escape(f.explanation)}</em></p>" if f.explanation else ""
            ),
            evidence_html=_evidence_img(f),
        )
        for f in findings
    )

    references_html = "\n".join(
        f'<div class="ref">• <a href="{html_lib.escape(r["url"])}">{html_lib.escape(r.get("title") or r["url"])}</a></div>'
        for r in references
    ) or "<p>No external references attached.</p>"

    score_color = "#27ae60" if score >= 80 else "#f39c12" if score >= 50 else "#e74c3c"

    return REPORT_HTML_TEMPLATE.format(
        url=html_lib.escape(url),
        page_count=page_count,
        score=score,
        score_color=score_color,
        summary=html_lib.escape(summary).replace("\n", "<br>"),
        finding_count=len(findings),
        findings_html=findings_html or "<p>No dark patterns detected.</p>",
        references_html=references_html,
    )


def generate_pdf_bytes(
    url: str,
    page_count: int,
    score: int,
    summary: str,
    findings: list[DetectedFinding],
    references: list[dict],
) -> bytes:
    """Render the report to PDF bytes."""
    html = build_html(url, page_count, score, summary, findings, references)
    from weasyprint import HTML

    return HTML(string=html).write_pdf()
