"""PDF report generator using WeasyPrint."""

import logging
from pathlib import Path

from app.agents.state import DetectedFinding

logger = logging.getLogger(__name__)

REPORT_HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #1a1a2e; }}
  h1 {{ color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 10px; }}
  h2 {{ color: #0f3460; margin-top: 30px; }}
  .score {{ font-size: 48px; font-weight: bold; color: {score_color}; }}
  .score-label {{ font-size: 14px; color: #666; }}
  .finding {{ border: 1px solid #ddd; border-radius: 8px; padding: 16px; margin: 12px 0; }}
  .finding-header {{ display: flex; align-items: center; gap: 8px; margin-bottom: 8px; }}
  .severity {{ padding: 2px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; color: white; }}
  .severity-high {{ background: #e74c3c; }}
  .severity-medium {{ background: #f39c12; }}
  .severity-low {{ background: #f1c40f; color: #333; }}
  .category {{ font-size: 12px; color: #888; }}
  .meta {{ font-size: 12px; color: #999; margin-top: 20px; }}
</style>
</head>
<body>
  <h1>Pattern Proof — Dark Pattern Audit Report</h1>
  <p><strong>Website:</strong> {url}</p>
  <p><strong>Pages analyzed:</strong> {page_count}</p>

  <div>
    <span class="score">{score}</span>
    <span class="score-label">/ 100 (higher is better)</span>
  </div>

  <h2>Executive Summary</h2>
  <p>{summary}</p>

  <h2>Findings ({finding_count})</h2>
  {findings_html}

  <p class="meta">Generated by Pattern Proof</p>
</body>
</html>"""

FINDING_HTML = """<div class="finding">
  <div class="finding-header">
    <span class="severity severity-{severity}">{severity_upper}</span>
    <strong>{title}</strong>
    <span class="category">{category} / {dp_type}</span>
  </div>
  <p>{description}</p>
  {explanation_html}
</div>"""


def generate_pdf(
    output_path: str,
    url: str,
    page_count: int,
    score: int,
    summary: str,
    findings: list[DetectedFinding],
) -> str:
    """Generate a PDF audit report and return the file path."""
    findings_html = "\n".join(
        FINDING_HTML.format(
            severity=f.severity,
            severity_upper=f.severity.upper(),
            title=f.title,
            category=f.category,
            dp_type=f.dp_type,
            description=f.description,
            explanation_html=f"<p><em>{f.explanation}</em></p>" if f.explanation else "",
        )
        for f in findings
    )

    score_color = "#27ae60" if score >= 80 else "#f39c12" if score >= 50 else "#e74c3c"

    html = REPORT_HTML_TEMPLATE.format(
        url=url,
        page_count=page_count,
        score=score,
        score_color=score_color,
        summary=summary,
        finding_count=len(findings),
        findings_html=findings_html or "<p>No dark patterns detected.</p>",
    )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    try:
        from weasyprint import HTML

        HTML(string=html).write_pdf(output_path)
        logger.info("PDF report written to %s", output_path)
    except ImportError:
        # Fallback: save as HTML if WeasyPrint not available
        html_path = output_path.replace(".pdf", ".html")
        Path(html_path).write_text(html, encoding="utf-8")
        logger.warning("WeasyPrint not available; saved HTML to %s", html_path)
        return html_path

    return output_path
